server:
  port: 8762
spring:
  application:
    name: gateway-server
ribbon:
  ReadTimeout: 60000
zuul:
  routes:
    customers:
      path: /customer-service/**
      serviceId: CUSTOMERBUSINESSSERVICES